language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
before_script:
  - cd spec/dummy
  - bundle exec rake db:migrate RAILS_ENV=test
  - cd ../..
script: bundle exec rspec
